PAD_RIGHT  = &01
PAD_LEFT   = &02
PAD_DOWN   = &04
PAD_UP     = &08
PAD_START  = &10
PAD_SELECT = &20
PAD_B      = &40
PAD_A      = &80

MAP_LEVELS = 50

MAP_WIDTH = 32
MAP_HEIGHT = 13

MAP_HERE   = &00
MAP_RIGHT  = &01
MAP_UP     = &02
MAP_LEFT   = &03
MAP_DOWN   = &04

MAP_EMPTY        = 0
MAP_CONCRETE     = 1
MAP_BRICK        = 2
MAP_BOMB         = 3
MAP_HIDDEN_EXIT  = 4
MAP_HIDDEN_BONUS = 5
MAP_BONUS        = 6
MAP_EXIT         = 8
